import cv2
import numpy as np
import time
from app.models import SignalResult

class S3TextureDetector:
    """
    S3: Skin Texture / High-Frequency Detail Signal.
    
    Detects GAN-smoothed skin — deepfakes generated by neural networks
    typically suppress high-frequency texture (pores, fine lines, wrinkles).
    
    Algorithm:
    1. Isolate skin ROI using face landmarks (cheek and forehead regions)
    2. Apply Laplacian to measure sharpness / texture detail
    3. Apply multi-scale frequency analysis (band-pass filtering)
    4. Compare high-freq energy ratio: real faces have ~15-35% HF content
       deepfakes often drop below 8% or have unnatural uniformity
    5. LBP uniformity score: real faces have higher LBP entropy
    
    Score: 0.0 = natural texture, 1.0 = GAN-smooth / suspicious
    """
    
    # Cheek and forehead landmark indices for skin sampling
    LEFT_CHEEK = [116, 123, 147, 187, 207, 213, 192, 214, 210, 211]
    RIGHT_CHEEK = [345, 352, 376, 411, 427, 433, 416, 434, 430, 431]
    FOREHEAD = [10, 338, 297, 332, 284, 251, 389, 356, 454, 323, 361, 288, 397, 365, 379, 378, 400, 377, 152]
    
    def __init__(self):
        self.last_hf_ratio = 0.0
        self.last_lbp_entropy = 0.0
        self.last_lap_var = 0.0
    
    def _extract_skin_patches(self, frame_bgr: np.ndarray, landmarks: np.ndarray) -> list:
        """Extract small skin patches from cheek regions."""
        h, w = frame_bgr.shape[:2]
        patches = []
        
        for region_indices in [self.LEFT_CHEEK, self.RIGHT_CHEEK]:
            pts = landmarks[region_indices, :2]  # xy normalized
            px = (pts * [w, h]).astype(int)
            
            # Get bounding box of this region
            x1, y1 = np.maximum(0, px.min(axis=0))
            x2, y2 = np.minimum([w-1, h-1], px.max(axis=0))
            
            if x2 > x1 + 10 and y2 > y1 + 10:
                patch = frame_bgr[y1:y2, x1:x2]
                patches.append(patch)
        
        return patches
    
    def _compute_lbp_entropy(self, gray_patch: np.ndarray) -> float:
        """Compute Local Binary Pattern entropy. Real faces = higher entropy."""
        rows, cols = gray_patch.shape
        lbp = np.zeros_like(gray_patch, dtype=np.uint8)
        
        for dy, dx in [(-1,-1),(-1,0),(-1,1),(0,1),(1,1),(1,0),(1,-1),(0,-1)]:
            shifted = np.roll(np.roll(gray_patch, dy, axis=0), dx, axis=1)
            bit = (gray_patch >= shifted).astype(np.uint8)
            lbp = (lbp << 1) | bit
        
        # Histogram of LBP codes
        hist, _ = np.histogram(lbp.flatten(), bins=256, range=(0, 256))
        hist = hist / (hist.sum() + 1e-10)
        # Shannon entropy (higher = more texture variety = more natural)
        entropy = float(-np.sum(hist * np.log2(hist + 1e-10)))
        return entropy
    
    def _compute_hf_ratio(self, gray_patch: np.ndarray) -> float:
        """High-frequency energy ratio using Fourier transform."""
        if gray_patch.shape[0] < 16 or gray_patch.shape[1] < 16:
            return 0.15  # Default: assume natural
        
        f = np.fft.fft2(gray_patch.astype(float))
        fshift = np.fft.fftshift(f)
        magnitude = np.abs(fshift)
        
        rows, cols = gray_patch.shape
        cy, cx = rows // 2, cols // 2
        
        # Define low-frequency region (inner 20% of spectrum)
        r_low = min(cy, cx) // 5
        y, x = np.ogrid[:rows, :cols]
        dist = np.sqrt((x - cx)**2 + (y - cy)**2)
        
        low_mask = dist <= r_low
        total_energy = magnitude.sum() + 1e-10
        low_energy = magnitude[low_mask].sum()
        hf_energy = total_energy - low_energy
        
        return float(hf_energy / total_energy)
    
    def process(self, frame_bgr: np.ndarray, landmarks: np.ndarray) -> SignalResult:
        now = time.time()
        
        if frame_bgr is None or landmarks is None or len(landmarks) < 468:
            return SignalResult(
                signal='S3',
                score=0.0,
                confidence=0.0,
                status='NORMAL',
                reason='No landmark data',
                timestamp=now
            )
        
        patches = self._extract_skin_patches(frame_bgr, landmarks)
        
        if not patches:
            return SignalResult(
                signal='S3',
                score=0.0,
                confidence=0.0,
                status='NORMAL',
                reason='No skin patches extracted',
                timestamp=now
            )
        
        hf_ratios = []
        lbp_entropies = []
        lap_vars = []
        
        for patch in patches:
            if patch.size == 0:
                continue
            gray = cv2.cvtColor(patch, cv2.COLOR_BGR2GRAY)
            
            # 1. Laplacian variance (texture sharpness)
            lap = cv2.Laplacian(gray, cv2.CV_64F)
            lap_vars.append(float(np.var(lap)))
            
            # 2. High-frequency energy ratio
            hf_ratios.append(self._compute_hf_ratio(gray))
            
            # 3. LBP entropy
            lbp_entropies.append(self._compute_lbp_entropy(gray))
        
        if not hf_ratios:
            return SignalResult(
                signal='S3',
                score=0.0,
                confidence=0.2,
                status='NORMAL',
                reason='Insufficient patch data',
                timestamp=now
            )
        
        mean_hf = float(np.mean(hf_ratios))
        mean_lbp = float(np.mean(lbp_entropies))
        mean_lap = float(np.mean(lap_vars))
        
        self.last_hf_ratio = mean_hf
        self.last_lbp_entropy = mean_lbp
        self.last_lap_var = mean_lap
        
        # Base camera optical calibration:
        # Standard webcams have sensor denoising and 480p/720p optics.
        # Real human skin typically has HF ratio 0.06-0.30; GAN deepfakes drop below 0.035.
        hf_score = 0.0
        if mean_hf < 0.040:
            hf_score = min(1.0, (0.040 - mean_hf) / 0.035)
        elif mean_hf > 0.55:
            hf_score = min(1.0, (mean_hf - 0.55) / 0.30)
        
        # Real skin on base webcam has LBP entropy 4.4-7.5 bits; synthetic skin drops below 3.8
        lbp_score = 0.0
        if mean_lbp < 3.8:
            lbp_score = min(1.0, (3.8 - mean_lbp) / 2.2)
        
        # Laplacian on base webcam cheek patches is typically 15-80; GAN smoothed drops below 10
        lap_score = 0.0
        if mean_lap < 12:
            lap_score = min(1.0, (12 - mean_lap) / 10.0)
        
        # Weighted combination
        score = 0.45 * hf_score + 0.35 * lbp_score + 0.20 * lap_score
        score = float(np.clip(score, 0.0, 1.0))
        
        confidence = 0.75  # Texture analysis is fairly reliable
        
        status = 'NORMAL'
        if score >= 0.65:
            status = 'ALERT'
        elif score >= 0.35:
            status = 'WARNING'
        
        label = 'Natural texture' if score < 0.35 else ('Smooth anomaly' if score < 0.65 else 'GAN-smooth skin detected')
        reason = f'HF: {mean_hf:.2f} | LBP: {mean_lbp:.1f}bits | LapVar: {mean_lap:.0f} — {label}'
        
        return SignalResult(
            signal='S3',
            score=float(score),
            confidence=float(confidence),
            status=status,
            reason=reason,
            timestamp=now
        )
